{% set name = "marshmallow" %}
{% set version = "2.13.1" %}
{% set sha256 = "cf7e35ddfe8b18f8de3058fffc621921c79bb07455ad3084bfbf64caca766711" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - marshmallow

about:
  home: http://github.com/marshmallow-code/marshmallow
  license: MIT
  license_file: LICENSE
  summary: 'A lightweight library for converting complex datatypes to and from native Python datatypes.'

  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for
    converting complex datatypes, such as objects, to and from
    native Python datatypes.
  doc_url: http://marshmallow.readthedocs.io/en/latest/
  dev_url: https://github.com/marshmallow-code/marshmallow/

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
    - carlodri
