{% set name = "marshmallow" %}
{% set version = "3.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90032c0fd650ce94b6ec6dc8dfeb0e3ff50c144586462c389b81a07205bedb78

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - packaging >=17.0

test:
  source_files: tests/*.py
  imports:
    - marshmallow
  commands:
    - pip check
    - python -m pytest tests
  requires:
    - pip
    - pytest
    - simplejson
    - pytz

about:
  home: https://github.com/marshmallow-code/marshmallow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight library for converting complex datatypes to and from native Python datatypes.
  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for
    converting complex datatypes, such as objects, to and from
    native Python datatypes.
  doc_url: https://marshmallow.readthedocs.io
  dev_url: https://github.com/marshmallow-code/marshmallow

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
    - carlodri
    - mariusvniekerk
