{% set name = "marshmallow" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1d860bd262737cb2d34e1541b84cb52c32c72c9474e3fe6f30f137ef8b0d97f

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - backports-datetime-fromisoformat  # [py<311]
    - typing-extensions  # [py<311]    

test:
  imports:
    - marshmallow
    - marshmallow.constants
    - marshmallow.decorators
    - marshmallow.error_store
    - marshmallow.exceptions
    - marshmallow.orderedset
    - marshmallow.schema
    - marshmallow.utils
    - marshmallow.validate
  source_files: 
    - tests/*.py
  commands:
    - pip check
    - pytest -vv tests  # [not win]
    - pytest -vv tests -k "not test_from_timestamp_with_overflow_value"  # [win]
  requires:
    - pip
    - pytest
    - simplejson
    - pytz
  #downstream:
  #  - marshmallow-enum
  #  - marshmallow-sqlalchemy
  #  - dataclasses-json
  #  - marshmallow-oneofschema
  #  - great-expectations
  #  - webargs
  #  - flask-appbuilder
  #  - unstructured-client
  #  - azure-ai-ml
  #  - environs

about:
  home: https://github.com/marshmallow-code/marshmallow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight library for converting complex datatypes to and from native Python datatypes.
  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for
    converting complex datatypes, such as objects, to and from
    native Python datatypes.
  doc_url: https://marshmallow.readthedocs.io
  dev_url: https://github.com/marshmallow-code/marshmallow

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
    - carlodri
    - mariusvniekerk
