{% set name = "marshmallow" %}
{% set version = "2.15.0" %}
{% set sha256 = "d3f31fe7be2106b1d783cbd0765ef4e1c6615505514695f33082805f929dd584" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - marshmallow

about:
  home: http://github.com/marshmallow-code/marshmallow
  license: MIT
  license_file: LICENSE
  summary: 'A lightweight library for converting complex datatypes to and from native Python datatypes.'

  description: |
    marshmallow is an ORM/ODM/framework-agnostic library for 
    converting complex datatypes, such as objects, to and from 
    native Python datatypes.
  doc_url: http://marshmallow.readthedocs.io/en/latest/
  dev_url: https://github.com/marshmallow-code/marshmallow/

extra:
  recipe-maintainers:
    - hajapy
    - rth
    - frol
    - igortg
