travis:
  secure:
    BINSTAR_TOKEN: TMjfpVGDQd1A+QxF89iefWMb8fbWdcdQk7DIUBDrMtaN62i4wI7TrUlb1QUaVeV7uHkqmaz1nGkwRr5y8GETNEF95/BtDoxku4rnhp1M3dn5uZ+tXhq5xUDs4k4QIdAlN8NoeQYBD0XbBzRWxE3/vLyuA4ywjSP8Pa5b25fepDLuxwM7NRKMLijx38Gwh31Dp3nj+/MgbMUbtAKCHbhLd6hOWVsLNZZr76i9UBrb0QRDvox3YN/W6izd1yejs9/p0aZr1tUmJg8ConoiOHO2TF/UMZzjZm263e2dIhGdm8qWBpNVBJHVtRioSiZCGR4oryURT1dYj13u4gUDZng7GPIHPRLk1Yx9kBBs4NVGC0SdC5pY6jiEG1rAKvdmp3O1F2QvUTQVXEwkdcyEDQJP6+yO5CsNem/OlJmKMTEYa9rvQfirpnY9B0An2cpL/r3Aq/v5j8nqWBy+EM1JbNugwZWjbHgOt9gwxAngPokQXSr5+C1OHWBkhIDdNjYdC9gMtJH0lYbIc6difezftCs7GIKZ3EXAym5pepIhxJWKG4+26VFM+1O1FnUlIvllGAgu6cUKCLMYosD01LjnALD8cOPsz4Evb+kIHb/YBJMwbZ7w0fr0cik2yIvhPpC2U5eV1F/ylZrgSxEsOEtQDYno1hsxN847lWSMyf1poxNtGHY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
